boschologie/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include

urlpatterns = [
    path('', lambda r: HttpResponseRedirect('jeugd/')),
    path('admin/', admin.site.urls),
    path('jeugd/', include('jeugd.urls')),
]

jeugd/urls.py
from django.urls import path

from . import views

app_name = 'jeugd'
urlpatterns = [
    path('', views.index, name='index'),
    path('lectures/', views.lectures, name='lectures'),
    path('lecture/', views.lecture, name='lecture'),
]

jeugd/models.py
from django.db import models

# Create your models here.

jeugd/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'jeugd/index.html')


def lectures(request):
    return render(request, 'jeugd/lectures.html')


def lecture(request):
    return render(request, 'jeugd/lecture.html')

jeugd/templates/jeugd/base.html
{% load staticfiles %}

<html>
<head>
    <title>{% block page_title %}{% endblock page_title %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" />

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</head>

<body>
{% include 'jeugd/navigation.html' %}
{% block content %}

{% endblock content %}
</body>
</html>

jeugd/templates/jeugd/index.html
{% extends 'jeugd/base.html' %}
{% load staticfiles %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<div>
    <div id="title-block">
        <h1 id="title">Jeugd Boschlogie</h1>
    </div>
    <div class="container-fluid">
        <div id="carouselExample" class="carousel slide" data-ride="carousel" data-interval="9000">
            <div class="carousel-inner row w-100 mx-auto" role="listbox">
                <div class="carousel-item col-md-4 active">
                    <a href="{% url 'jeugd:lectures' %}">
                        <img class="img-fluid mx-auto d-block"
                             src="{% static 'images/index/01-drakenfontein-den-bosch-1024x678.jpg' %}" alt="slide 1">
                        <div class="theme-description">
                            <h5>
                                Thema 1: Schatten van de Draak
                            </h5>
                        </div>
                    </a>
                </div>
                <div class="carousel-item col-md-4">
                    <a href="{% url 'jeugd:lectures' %}">
                        <img class="img-fluid mx-auto d-block" src="{% static 'images/index/BMN6480.jpg' %}"
                             alt="slide 2">
                        <div class="theme-description">
                            <h5>
                                Thema 2: Jheronimus Bosch
                            </h5>
                        </div>
                    </a>
                </div>
                <div class="carousel-item col-md-4">
                    <a href="{% url 'jeugd:lectures' %}">
                        <img class="img-fluid mx-auto d-block" src="{% static 'images/index/DenBosch-5.jpg' %}"
                             alt="slide 3">
                        <div class="theme-description">
                            <h5>
                                Thema 3: Sint Jan
                            </h5>
                        </div>
                    </a>
                </div>
                <div class="carousel-item col-md-4">
                    <a href="{% url 'jeugd:lectures' %}">
                        <img class="img-fluid mx-auto d-block"
                             src="{% static 'images/index/oeteldonk-carnavalsoptocht.jpg' %}" alt="slide 4">
                        <div class="theme-description">
                            <h5>
                                Thema 4: Oeteldonk
                            </h5>
                        </div>
                    </a>
                </div>
                <div class="carousel-item col-md-4">
                    <a href="{% url 'jeugd:lectures' %}">
                        <img class="img-fluid mx-auto d-block" src="{% static 'images/index/Binnendieze.jpg' %}"
                             alt="slide 5">
                        <div class="theme-description">
                            <h5>
                                Thema 5: Binnendieze
                            </h5>
                        </div>
                    </a>
                </div>
                <!--<div class="carousel-item col-md-4">-->
                    <!--<a href="{% url 'jeugd:lectures' %}">-->
                        <!--<img class="img-fluid mx-auto d-block"-->
                             <!--src="{% static 'images/index/92ba276c35d4717b7e32572429b6a993&#45;&#45;bosch.jpg' %}"-->
                             <!--alt="slide 6">-->
                        <!--<div class="theme-description">-->
                            <!--<h5>-->
                                <!--Thema 6: Knillis-->
                            <!--</h5>-->
                        <!--</div>-->
                    <!--</a>-->
                <!--</div>-->
                <div class="carousel-item col-md-4">
                    <a href="{% url 'jeugd:lectures' %}">
                        <img class="img-fluid mx-auto d-block" src="{% static 'images/index/tuighuis.jpg' %}"
                             alt="slide 7">
                        <div class="theme-description">
                            <h5>
                                Thema 6: Groot Tuighuis
                            </h5>
                        </div>
                    </a>
                </div>
                <div class="carousel-item col-md-4">
                    <a href="{% url 'jeugd:lectures' %}">
                        <img class="img-fluid mx-auto d-block" src="{% static 'images/index/marienburg.jpg' %}"
                             alt="slide 8">
                        <div class="theme-description">
                            <h5>
                                Thema 7: Marienburg
                            </h5>
                        </div>
                    </a>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
                <i class="fa fa-chevron-left fa-lg text-muted"></i>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next text-faded" href="#carouselExample" role="button" data-slide="next">
                <span class="carousel-control-next-icon"></span>
                <i class="fa fa-chevron-right fa-lg text-muted"></i>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<link rel="stylesheet" href="{% static 'css/carousel.css' %}">
<script src="{% static 'scripts/carousel.js' %}"></script>
{% endblock %}

jeugd/templates/jeugd/lecture.html
{% extends 'jeugd/base.html' %}
{% load staticfiles %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/lecture.css' %}">

<div id="outer-container">
    <h1>Les 1: Jheronimus Bosch, wie was dat nu eigenlijk?</h1>
</div>
<img id="stamboom" src="{% static 'images/lecture/stamboom.png' %}">
<img id="jheronimus" src="{% static 'images/lecture/250px-Jheronimus_Bosch_(cropped).jpg' %}">
<div id="jheronimus-description"><h6><b>Jheronimus Bosch<br>('s-Hertogenbosch, circa 1450 - 9 augstus 1516)</b></h6></div>
<img id="tijdlijn" src="{% static 'images/lecture/60508a8e266c4294a9eb98f7040d460b3647ebf1.jpg' %}">
<img id="arrow" src="{% static 'images/lecture/arrow.png' %}">



{% endblock %}

jeugd/templates/jeugd/lectures.html
{% extends 'jeugd/base.html' %}
{% load staticfiles %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/lectures.css' %}">

<div id="outer-container">
    <h1>Jheronimus Bosch</h1>
    <div class="lecture row">
        <a href="{% url 'jeugd:lecture' %}">
            <div class="row">
                <div class="col col-sm-1"><img
                        src="{% static 'images/lectures/250px-Jheronimus_Bosch_(cropped).jpg' %}"></div>
                <div class="question col col-sm-2"><p><br><br>Les 1: Jheronimus Bosch, wie was dat nu eigenlijk?</p></div>
                <div class="description col col-sm-8"><p><br><br>In deze les leren de kinderen, wie Jeroen Bosch was: In welke
                    tijd leefde hij en hoe
                    zag 's-Hertogenbosch er toen uit? Wat heeft deze man allemaal gedaan in zijn leven, en waarom is hij
                    belangrijk voor 's-Hertogenbosch?</p></div>
                <div class="lecture-type col col-sm-1">
                    <div class="m-2">
                        <div class="row"><p>Digiboard Les</p></div>
                        <div class="row"><p>Bronnenblad</p></div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <div class="lecture row">
        <a href="{% url 'jeugd:lecture' %}">
            <div class="row">
                <div class="col col-sm-1"><img
                        src="{% static 'images/lectures/de_tuin_der_lusten.jpg' %}">
                </div>
                <div class="question col col-sm-2"><p><br><br>Les 2: Goed en kwaad in de Tuin der Lusten.</p></div>
                <div class="description col col-sm-8"><p><br><br>In les 2 bestuderen de kinderen het meesterwerk van Jeroen
                    Bosch: De tuin der Lusten. Door middel van hun eigen creativiteit leren de kinderen hoe het
                    schilderij geïntepreteerd kan worden.</p></div>
                <div class="lecture-type col col-sm-1">
                    <div class="m-2">
                        <div class="row"><p>Digiboard Les</p></div>
                        <div class="row"><p>Bronnenblad</p></div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <div class="lecture row">
        <a href="{% url 'jeugd:lecture' %}">
            <div class="row">
                <div class="col col-sm-1"><img
                        src="{% static 'images/lectures/hieronymus_bosch_3_529_548_80.jpeg' %}"></div>
                <div class="question col col-sm-2"><p><br><br>Les 3: Jheronimus Bosch en 's-Hertogenbosch nu.</p></div>
                <div class="description col col-sm-8"><p><br><br>Les 3 legt het veraband tussen het verleden en heden. Wat
                    merken we nu nog van de invloed va nJheronimus Bosch? Deze les stimuleert de kinderen om de stad
                    actief te ontdekken.</p></div>
                <div class="lecture-type col col-sm-1">
                    <div class="m-2">
                        <div class="row"><p>Digiboard Les</p></div>
                        <div class="row"><p>Bronnenblad</p></div>
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>

{% endblock %}

jeugd/templates/jeugd/navigation.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/navigation.css' %}">

<nav id="primary-navigation" class="navbar navbar-expand-lg navbar-light navbar-fixed-top" role="navigation">
    <a class="navbar-brand" href="{% url 'jeugd:index' %}">
        <img src="{% static 'images/logo.png' %}" width="50" height="40" class="d-inline-block align-top"
             alt="Logo">
    </a>

    <button class="navbar-toggler navbar-left pull-left" type="button" data-toggle="collapse" data-target="#navbar-primary"
            aria-controls="navbar-primary" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar-primary">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'jeugd:index' %}">Home<span
                        class="sr-only">(current)</span></a>
            </li>
        </ul>

    </div>

    <a id="boschologie-brand" class=" mx-auto navbar-right pull-right" href="https://www.erfgoedshertogenbosch.nl/">
        <img src="{% static 'images/logo_S-hertogenbosch@2x.png' %}" width="150" height="30" alt="Boschologie">
    </a>
</nav>